### ISSUE TITLE
regenerating renshuu API key seems to break the connection

### ISSUE THREAD

**Issue by oscarwong67** [ikuto0815/renshuu-connect#1]
At one point I regenerated my renshuu read/write API key, and the new key never seems to work with renshuu connect.

E.g. I get an error like:

```
{
    "error": {
        "name": "ExtensionError",
        "_data": {
            "action": "version",
            "params": {},
            "originalError": {}
        }
    }
}
ExtensionError: Anki connection failure
    at AnkiConnect._invoke (chrome-extension://likgccmbimhjbgkjambclfkhldnlhbnn/js/comm/anki-connect.js:445:27)
    at async AnkiConnect._getVersion (chrome-extension://likgccmbimhjbgkjambclfkhldnlhbnn/js/comm/anki-connect.js:551:25)
message: Anki connection failure
```

**Comment by ikuto0815** [comment]
Hi,
I think it's an issue with renshuu itself.
The swagger API page also returns a "invalid API key" error when I try it there. https://api.renshuu.org/docs/#/User/get_profile

Can you also confirm that?

**Comment by oscarwong67** [comment]
> Hi, I think it's an issue with renshuu itself. The swagger API page also returns a "invalid API key" error when I try it there. https://api.renshuu.org/docs/#/User/get_profile
> 
> Can you also confirm that?

Surprisingly, it seemed to work for me with the API key from my signed in https://www.renshuu.org/index.php?page=misc/api page

![image](https://github.com/user-attachments/assets/8a7da661-b456-438d-b1d1-a44fcc02bf1a)

**Comment by ikuto0815** [comment]
If you copy the key from the API page again into the the yomitan config, does it then work?
I noticed that the api key page shows a 128 character long key after you press the button to generate a new key. (using this causes the error)
If you go to the dashboard in renshuu, then back to the api page, it will now only show the first 64 characters. (this is the actual working key)
I also reported this to Michael.

**Comment by ikuto0815** [comment]
Try regenerating the API key and using the new one. The issue with renshuu generating a too long key was just fixed.

**Comment by oscarwong67** [comment]
Strangely, I never got the 128 character long key, and it still doesn't work in Yomitan for me! You're using the read-write one, right?

For more context, it still works in Swagger.

**Comment by ikuto0815** [comment]
I created a new release v0.4 yesterday. It doesn't fix any issues but should improve the error messages that renshuu-connect sends back to yomitan.

Also I notices something weird. In your original message, it shows that the action `version` caused an error. That endpoint in renshuu-connect just returns the value `"2"`. It doesn't even use the API key in any form.

Actually, the last line says `message: Anki connection failure`. Are you sure renshuu-connect is running and you entered the correct address?

You can check it by opening http://127.0.0.1:8765/docs in your browser.

**Comment by oscarwong67** [comment]
It turns out I'm an idiot and didn't realize I had to run the exe every time, my bad. Thanks for your patience on this issue 🥲

**Comment by ikuto0815** [comment]
No worries. after all, there was an actual bug discovered thanks to this issue.

The windows version has a tray icon (just some black and white squares, I didn't have time to make a proper icon) you can use to check if it's running. You can also stop the app by clicking the icon which should open a menu.

I was thinking of adding a autostart feature, but didn't have time yet to think about hot to do that. Personally, I run renshuu-connect on a server, so I just start it once and it's running for months.
